/* Source-linked onboarding and live research. Every run is executed by the API. */
(function(scope){
  'use strict';
  function create(b,x,h){
    const {e,button,heading,read,ref,navigate,sourceDetails,ask}=h;
    Object.assign(x,{briefRef:null,watchRunRef:null,discoveryRef:null,followRun:null,connectBusy:false,
      telemetryContent:'',connectSource:'',aiBrief:null,discoveryJob:null,discoveryRecords:[],discoveryLoaded:false,flowEpoch:0,
      planRef:null,simulatorRef:null,executionRef:null,buildBusy:false,runBusy:false,planBusy:false,signalCode:null,
      draft:{question:'',
        control_text:'',
        treatment_text:'',
        trials_per_arm:2,max_rounds:6,valid_probability:0.35,seed:61005}});
    const post=(path,body)=>b.api(path,{method:'POST',headers:{'Content-Type':'application/json','X-Lab-Token':b.app.state.csrf},body:JSON.stringify(body)});
    const jobStatus=()=>b.app.state.jobs.find(j=>j.id===x.discoveryJob);
    function save(){try{sessionStorage.setItem('society-journey',JSON.stringify({briefRef:x.briefRef,watchRunRef:x.watchRunRef,project:x.project,discoveryRef:x.discoveryRef,followRun:x.followRun,discoveryJob:x.discoveryJob,planRef:x.planRef,simulatorRef:x.simulatorRef,executionRef:x.executionRef,draft:x.draft,signalCode:x.signalCode,study:x.study,aiBrief:x.aiBrief}));}catch(_) {}x.onWorkspaceSave?.();}
    try{const raw=sessionStorage.getItem('society-journey');const saved=raw && raw.length<32000?JSON.parse(raw):null;if(saved && typeof saved==='object'){
      for(const key of ['briefRef','watchRunRef','project','discoveryRef','planRef','simulatorRef','executionRef','study']){const v=saved[key];if(v===null || (v && typeof v.id==='string' && /^[A-Za-z0-9_.-]{1,200}$/.test(v.id) && Number.isSafeInteger(v.version) && v.version>0 && /^[a-f0-9]{64}$/.test(v.hash)))x[key]=v;}
      for(const key of ['followRun','discoveryJob','signalCode'])if(saved[key]===null || (typeof saved[key]==='string' && saved[key].length<=200))x[key]=saved[key];
      if(typeof saved.aiBrief==='string' && saved.aiBrief.length<=6000)x.aiBrief=saved.aiBrief;
      for(const key of ['question','control_text','treatment_text'])if(typeof saved.draft?.[key]==='string' && saved.draft[key].length<=2000)x.draft[key]=saved.draft[key];
      for(const [key,lo,hi] of [['trials_per_arm',2,20],['max_rounds',2,12],['valid_probability',0,1],['seed',0,9007199254740991]]){const v=saved.draft?.[key];if(typeof v==='number' && Number.isFinite(v) && v>=lo && v<=hi && (key==='valid_probability' || Number.isSafeInteger(v)))x.draft[key]=v;}
    }}catch(_){}
    function invalidate(){x.flowEpoch++;x.planRef=null;x.simulatorRef=null;x.executionRef=null;save();}
    function applyDraft(draft){if(!draft)return;let changed=false;for(const key of ['question','control_text','treatment_text'])if(typeof draft[key]==='string' && draft[key].trim() && draft[key].length<=2000 && draft[key]!==x.draft[key]){x.draft[key]=draft[key];changed=true;}if(changed)invalidate();}
    async function accept(packet){
      const sameSource=x.briefRef?.hash===packet.brief_ref?.hash,priorJob=jobStatus(),reuseJob=sameSource && x.discoveryRef?.hash===packet.discovery_ref?.hash && priorJob?.status==='completed'?priorJob.id:null,priorBrief=sameSource?x.aiBrief:null;
      x.briefRef=packet.brief_ref;x.project=packet.dataset_ref || null;x.watchRunRef=packet.run_ref || null;
      x.followRun=packet.follow_ref?.id || null;x.discoveryRef=packet.discovery_ref || null;
      x.watchStudy=null;x.previewWatch=null;x.window='demo';x.aiBrief=priorBrief;x.discoveryRecords=[];x.discoveryLoaded=false;x.discoveryJob=reuseJob;if(b.app.workspace){x.flowEpoch++;if(!x.draftSourceRef)x.draftSourceRef=x.briefRef;}else invalidate();save();
      await b.refresh();await navigate('brief');
      // The connector has already saved a deterministic, bounded screen. Actual
      // investigators and a skeptic now examine evidence with their own tools.
      const connectedHash=x.briefRef.hash,connectedEpoch=x.flowEpoch;
      if(x.discoveryRef && !reuseJob){try{const response=await b.submit('investigate',{discovery_id:x.discoveryRef.id,discovery_version:x.discoveryRef.version,discovery_hash:x.discoveryRef.hash,count:2,live:true,harness:'responses'});if(x.flowEpoch===connectedEpoch && x.briefRef?.hash===connectedHash){x.discoveryJob=response?.job_id || null;save();await b.render();}}catch(error){b.toast('The initial screen is ready. The deeper AI search could not start: '+error.message,true);}}
      if(priorBrief || x.flowEpoch!==connectedEpoch)return;
      ask('Proactively brief me on this exact connected source in simple language. Label the analysis observational. Describe the source episode, competing explanations and one question to clarify. Identify the environment state and tools needed to discriminate them. Only use the selected AI Village source. Do not claim a historical mechanism or select a simulator before its required state is reviewed.',{proactive:true}).then(answer=>{if(answer?.answer_source==='ai' && !answer.stale_context && x.flowEpoch===connectedEpoch && x.briefRef?.hash===connectedHash){x.aiBrief=answer.answer;save();b.render();}});
    }
    async function connect(){
      const datasets=[];for(const entry of b.all('dataset').filter(r=>Number(r.summary?.messages)<=2000)){const full=await read(ref(entry),'dataset'),provenance=full.payload.provenance || {};if(provenance.origin!=='authored_example' && !String(full.payload.source || '').includes('coordination_fixture'))datasets.push({...entry,friendlyName:provenance.original_name || (provenance.source_sha256==='c1d56ab7b437f65c985c3353697d92f668f3a7b83776913aa5e3eb93ed867bb7'?'AI Village · '+String(provenance.scope?.start || '').slice(0,10):'Saved swarm chat')});}
      if(!datasets.some(r=>r.id===x.connectSource))x.connectSource=datasets.find(r=>r.id===scope.SocietyExperience?.DEMO.id)?.id || datasets[0]?.id || '';
      return heading('CONNECT','Start with what you have.','Connect agent-session logs. If you also have an environment, the guide can review its rules and tools with you.','connect')+
        `<section class="journey-card"><h2>Two ways to start</h2><div class="journey-comparison"><article><span class="eyebrow">LOGS ONLY · AI VILLAGE</span><h3>Discover what happened.</h3><p>The guide examines real messages and actions. A later experiment may use a new world with disclosed proxy tools.</p></article><article><span class="eyebrow">LOGS + AN ENVIRONMENT</span><h3>Bring a world to test in.</h3><p>Ask the guide to review your environment and tool contract. It checks what can be reproduced and which capabilities need a proxy.</p>${button('Discuss my existing environment','data-journey-existing-environment')}</article></div><p class="exp-small">Observed behaviour and experimental results keep separate source records. You can return to either at any time.</p></section>`+
        `<div class="journey-connect"><section class="journey-card"><span class="eyebrow">READY ON THIS LAPTOP</span><h2>Connect the AI Village data.</h2><p>This is recorded communication from real agents. We will screen the saved source, then send bounded excerpts to the configured research agents.</p><label class="field"><span>Saved source</span><select id="journey-source">${datasets.map(r=>`<option value="${e(r.id)}" ${r.id===x.connectSource?'selected':''}>${e(r.id===scope.SocietyExperience?.DEMO.id?'AI Village · 588 saved messages':r.friendlyName+' · '+r.summary?.messages+' messages')}</option>`).join('')}</select></label>${button(x.connectBusy?'Connecting…':'Connect and discover →',`data-journey-connect ${x.connectBusy || !datasets.length?'disabled':''}`,true)}<p class="exp-small">No new dataset download. Your original files stay as they are.</p></section>
        <section class="journey-card"><span class="eyebrow">YOUR RUNNING SWARM</span><h2>Connect a harness.</h2><p>Send agents, tasks, messages, tool results and interventions with the same event format. Your harness keeps doing the work.</p><div class="journey-protocol"><strong>societylab.events.v1</strong><code>POST /api/observability/connect</code><span>Stable event IDs · UTC times · explicit recipients</span></div><details><summary>Connect an event batch now</summary><label class="field"><span>Paste a JSON event batch</span><textarea id="journey-events" rows="6" placeholder="Paste events emitted by your harness">${e(x.telemetryContent)}</textarea></label><label class="field"><span>Or choose a JSON file</span><input id="journey-event-file" type="file" accept=".json,application/json"></label>${button('Connect recorded events',`data-journey-events ${x.connectBusy?'disabled':''}`)}</details><div class="action-row"><a class="button" href="/api/observability/schema" target="_blank" rel="noopener">See the event format ↗</a>${button('Import chat messages','data-view="import"')}</div><p class="exp-small">Only logged recipients make a communication edge. Missing task or delivery data stays unknown.</p></section></div>`;
    }
    async function getBrief(){return x.briefRef?read(x.briefRef,'observation_brief'):null;}
    function signalCards(p){return (p.signals || []).map(s=>`<article class="journey-signal"><span class="journey-tag ${e(s.severity)}">${e(s.interpretation==='observed'?'Logged event':'Pattern to check')}</span><h3>${e(s.title)}</h3><p>${e(s.question)}</p><details><summary>Other possible explanations</summary><ul>${(s.alternative_explanations || []).map(v=>`<li>${e(v)}</li>`).join('')}</ul><p>${s.evidence_message_ids?.length || s.evidence_event_ids?.length || 0} cited records. ${e(s.next_test_family?'Suggested test family: '+s.next_test_family:'No supported simulator is selected for this signal.')}</p></details><div class="action-row">${button('Replay evidence',`data-journey-evidence="${e(s.code)}"`)}${button('Explore this question',`data-journey-signal="${e(s.code)}"`)}</div></article>`).join('') || '<p>No configured pattern was found in this retained window. This does not show that the swarm has no other behavior.</p>';}
    async function loadDiscovery(){
      const job=jobStatus();if(x.discoveryLoaded || job?.status!=='completed')return;
      x.discoveryLoaded=true;const ids=Array.isArray(job.payload.result_ids)?job.payload.result_ids:[job.payload.result_ids];
      for(const id of ids.filter(v=>typeof v==='string')){const obj=await b.object(id);if(obj.kind==='behavior' && obj.payload.source_refs?.discovery?.id===x.discoveryRef?.id && obj.payload.source_refs?.discovery?.hash===x.discoveryRef?.hash)x.discoveryRecords.push(obj);}
    }
    async function brief(){
      const record=await getBrief();if(!record)return heading('DISCOVER','Connect a source first.','We need actual recorded events before we can describe your agents.','brief')+button('Connect agents →','data-view="connect"',true);
      await loadDiscovery();const p=record.payload,c=p.counts || {},job=jobStatus();
      const names=(p.agents || []).slice(0,8).map(a=>`<span class="journey-person"><i>${e((a.name || a.id || '?')[0])}</i>${e(a.name || a.id)}</span>`).join('');
      const deeper=x.discoveryRecords.map(r=>`<article class="journey-discovery"><span class="eyebrow">AI INVESTIGATOR + SKEPTIC REVIEW</span><h3>${e(r.payload.name || r.payload.title || r.id)}</h3><p>${e(String(r.payload.description || r.payload.hypothesis || r.payload.operational_definition || 'A source-linked candidate is saved in the behavior library.').slice(0,300))}</p><p class="exp-small">Candidate explanation. Novelty and causation are still unestablished.</p>${button('Open evidence and review',`data-exp-inspect="${e(r.id)}" data-exp-version="${r.version}"`)}</article>`).join('');
      return heading('DISCOVER','Here is what we can see.','Society Lab screens the data as soon as it connects. AI investigators examine candidate episodes and check other explanations.','brief')+
        `<section class="journey-brief-hero"><div><span class="eyebrow">YOUR CONNECTED SOURCE</span><h2>${e(c.task_ids===0 && c.agent_messages!==undefined?`This chat names ${c.known_agents} agents and includes ${c.agent_messages} posts from them. Tasks and tool results were not recorded.`:p.summary || 'The saved source is ready.')}</h2><div class="journey-people">${names}</div></div><div class="journey-counts"><article><strong>${c.agent_messages ?? c.known_agents ?? 0}</strong><span>${c.agent_messages!==undefined?'agent posts':'known agents'}</span></article><article><strong>${c.task_ids ?? 0}</strong><span>logged tasks</span></article><article><strong>${c.signals ?? p.signals?.length ?? 0}</strong><span>patterns to inspect</span></article></div><div class="action-row">${button('Watch agents talk →','data-journey-watch',true)}${button('Plan an experiment','data-view="plan"')}</div></section>
        <section class="journey-card journey-ai"><span class="eyebrow">AUTOMATIC AI BRIEF</span><p>${e(x.aiBrief || (x.guideBusy?'The AI guide is reading this source and drafting a question…':'Ask the guide to explain this source or help refine a question.'))}</p><div class="journey-job" role="status"><i class="${job?.status==='running' || job?.status==='queued'?'spinner':''}"></i>${e(job?job.status==='completed'?'The deeper search has finished.':job.status==='failed'?'The deeper search stopped. Its log is retained.':'Investigators and a skeptic are examining two source episodes.':'The bounded source screen is ready.')}${job?.status==='failed'?button('Inspect search log',`data-exp-inspect-job="${e(job.id)}"`):''}</div></section>
        <div class="exp-section-title"><h2>What deserves a closer look?</h2><p>Signals suggest questions. They do not reveal private intent.</p></div><div class="journey-signals">${signalCards(p)}</div>${deeper?`<div class="exp-section-title"><h2>What the research agents found</h2></div><div class="journey-signals">${deeper}</div>`:''}
        <section class="journey-card"><h2>What do you know that the logs do not?</h2>${(p.clarifications || []).map(q=>`<p>${e(typeof q==='string'?q:q.question || q.text || JSON.stringify(q))}</p>`).join('')}${button('Discuss this with the guide','data-journey-clarify')}<p class="exp-small">Your answers help define the next test. They do not change the retained events.</p></section>${sourceDetails(record,'Source and screening limits')}`;
    }
    async function plan(){
      const frozen=x.planRef?await read(x.planRef,'guided_plan'):null;
      if(['village_document_access_repair','single_document_reference_repair'].includes(frozen?.payload.family))return heading('PLAN','Review the source-grounded access comparison.','This plan came from the cited episode and hypothesis. Review its omissions before running fresh agents.','plan')+accessPlan(frozen)+`<div class="action-row">${button('Create or inspect this world','data-view="simulator"',true)}${button('Discuss a change to this plan','data-journey-help')}</div>`;
      return heading('PLAN','Plan a test from the AI Village episode.','The guide reviews the source, competing explanations and required state before a world is chosen.','plan')+`<section class="journey-card"><h2>Your source-linked question</h2><label class="field"><span>What should the experiment distinguish?</span><textarea id="journey-question" data-journey-field="question" rows="3" maxlength="2000">${e(x.draft.question)}</textarea></label><p>No simulator is automatically selected. The plan must identify the source episode, hypothesis, represented mechanisms and omitted state.</p>${button('Review this episode and propose a world','data-journey-help',true)}</section>`;
    }

    async function simulator(){
      if(!x.planRef)return heading('SIMULATE','Save a plan first.','The world is built from the question and comparison you review.','simulator')+button('Plan the experiment →','data-view="plan"',true);
      const planRecord=await read(x.planRef,'guided_plan'),p=planRecord.payload;
      const sim=x.simulatorRef?await read(x.simulatorRef,'guided_simulator'):null;
      if(['village_document_access_repair','single_document_reference_repair'].includes(p.family))return heading('SIMULATE','Model document access, references and repair.','Fresh agents act in an explicit access world. Account services and historical state are not silently reconstructed.','simulator')+accessPlan(planRecord,sim)+`<section class="journey-card">${sim?`<p>${sim.payload.boundary_checks?.passed?'The saved information-boundary checks passed.':'Review the saved boundary checks before execution.'} This does not establish historical fidelity.</p>${button(x.runBusy?'Agents are running…':'Run this source-grounded experiment',`data-journey-run ${x.runBusy?'disabled':''}`,true)}${x.executionRef?button('Open this study’s results','data-journey-result'):''}`:button(x.buildBusy?'Building and reviewing…':'Build and review this access world',`data-journey-build ${x.buildBusy?'disabled':''}`,true)}</section>`;
      return heading('SIMULATE','Review a Village-grounded plan first.','The saved plan must connect the task and access mechanism to the selected AI Village episode.','simulator')+button('Discuss the source and plan','data-journey-help',true);
    }

    function accessPlan(plan,world=null){
      const p=plan.payload,recovery=p.family==='single_document_reference_repair',s=world?.payload || p,f=s.fidelity || {},h=s.hypothesis || p.hypothesis || {},source=s.source_refs?.dataset_ref || p.source_refs?.dataset_ref;
      const list=v=>Array.isArray(v) && v.length?`<ul>${v.filter(x=>typeof x==='string').slice(0,24).map(x=>`<li>${e(x)}</li>`).join('')}</ul>`:'<p>Not recorded yet. The builder must disclose this before a fidelity claim.</p>';
      return `<section class="journey-card"><span class="eyebrow">DOCUMENT ACCESS AND REPAIR · TASK ANALOGUE</span><h2>${recovery?'Help one peer recover the original document.':'Test document access and project completion.'}</h2><details><summary>Exact saved research question</summary><p>${e(p.question)}</p></details><h3>What the team must do</h3><p>${recovery?'The owner and auditor share one explicit goal in both arms: the auditor must actually open the current original. Content and access rights start correct; its broken reference is the selected repair problem.':'Produce a project that its intended collaborators can use.'} ${recovery?'They can search by title, open exact references and send a direct peer message. Content, viewer access and starting authenticated profiles are held fixed; recreation and sharing tools are not part of this narrow task.':'Agents can encounter access, permission and reference failures and decide whether to check, repair or recreate project resources under the saved rules.'}</p><h3>Hypothesis</h3><p>${e(h.statement || 'No hypothesis statement recorded.')}</p><p><strong>Source episode:</strong> ${source?`${e(source.id)} · version ${e(source.version)} ${button('Inspect exact source',`data-exp-inspect="${e(source.id)}" data-exp-version="${e(source.version)}"`)}`:'Not pinned.'} ${p.grounding_ref?button('Inspect the selected incident',`data-exp-inspect="${e(p.grounding_ref.id)}" data-exp-version="${e(p.grounding_ref.version)}"`):''}</p><div class="journey-comparison"><article><h3>Neutral note</h3><p>${e(p.control_text || 'Not recorded')}</p></article><article><h3>Canonical project check</h3><p>${e(p.treatment_text || 'Not recorded')}</p></article></div><h3>What we estimate</h3><p>${recovery?'The change in executed auditor access to the one current original under the two assigned notes.':'The change in whole-team verified usable-project outcomes between these two assigned notes in this world.'} ${recovery?'Queued references and content inspections are descriptive secondary measures; they do not establish what anyone understood.':'Avoidable recreations are a separate process measure.'} This does not estimate the original historical cause.</p><div class="journey-comparison"><article><h3>Represented mechanisms</h3>${list(f.represented)}</article><article><h3>Approximated state and tools</h3>${list(f.approximated)}</article><article><h3>Omitted state</h3>${list(f.omitted)}</article></div><p class="exp-small">Historical equivalence is unestablished. A source citation motivates the hypothesis; it does not validate the simulator.</p>${world?sourceDetails(world,'Saved executable world and contract'):sourceDetails(plan,'Saved source-grounded plan')}</section>`;
    }
    async function click(target){
      if(target.hasAttribute('data-journey-existing-environment')){await ask('I have agent-session logs and an existing environment. Help me connect them. Ask for its saved artifact or environment/tool specification, review the adapter and information boundaries, and identify tools that need disclosed proxies. Do not claim that arbitrary environment code has been imported or execute it before a concrete plan is agreed.');return true;}
      if(target.hasAttribute('data-journey-connect')){if(x.connectBusy)return true;x.connectBusy=true;const epoch=x.flowEpoch;try{await b.render();const source=b.all('dataset').find(r=>r.id===x.connectSource);if(!source)throw new Error('Choose a saved source.');const full=await read(ref(source),'dataset');if(full.payload.provenance?.origin==='authored_example' || String(full.payload.source || '').includes('coordination_fixture') || Number(source.summary?.messages)>2000)throw new Error('Choose a recorded source of up to 2,000 messages. Software examples are excluded from this source list.');const packet=await post('/api/observability/brief',{dataset_ref:ref(source)});if(epoch===x.flowEpoch)await accept(packet);}finally{if(epoch===x.flowEpoch || epoch+1===x.flowEpoch)x.connectBusy=false;}return true;}
      if(target.hasAttribute('data-journey-events')){if(x.connectBusy)return true;x.connectBusy=true;const epoch=x.flowEpoch;try{const body=JSON.parse(x.telemetryContent);const packet=await post('/api/observability/connect',body);if(epoch===x.flowEpoch)await accept(packet);}finally{if(epoch===x.flowEpoch || epoch+1===x.flowEpoch)x.connectBusy=false;}return true;}
      if(target.hasAttribute('data-journey-watch')){x.watchStudy=null;await navigate('watch');return true;}
      if(target.hasAttribute('data-journey-clarify')){document.getElementById('guide-input').value='Context about my swarm: ';document.getElementById('guide-dock')?.classList.add('open');document.getElementById('guide-input').focus();return true;}
      if(target.hasAttribute('data-journey-help')){await ask('Review the exact source episode and our question. Identify competing explanations, document/tool/access state required to distinguish them, a target estimand and omitted historical state. Choose a supported source-grounded world only when its mechanism fits; otherwise report the missing capabilities. Use only source-grounded AI Village evidence. Do not execute subjects yet.');await b.render();return true;}

      if(target.hasAttribute('data-journey-signal')){x.signalCode=target.dataset.journeySignal;x.draftSourceRef=x.briefRef;invalidate();await navigate('plan');await ask('Review source-linked signal '+x.signalCode+' and propose a discriminating hypothesis. Identify the state/tools needed and disclosed fidelity limits before selecting an environment. Do not choose a world whose mechanisms differ from the source question.');await b.render();return true;}
      if(target.hasAttribute('data-journey-evidence')){const brief=await getBrief();const signal=brief.payload.signals.find(s=>s.code===target.dataset.journeyEvidence);x.evidenceIds=signal?.evidence_message_ids || [];x.evidenceEventIds=signal?.evidence_event_ids || [];x.watchStudy=null;await navigate('watch');return true;}
      if(target.hasAttribute('data-journey-plan')){await ask('Save a source-grounded AI Village experiment plan from the selected episode and our question. Retain the exact source, hypothesis and fidelity contract. Do not build or run agents yet.');return true;}
      if(target.hasAttribute('data-journey-build')){const selected=await read(x.planRef,'guided_plan');if(!['village_document_access_repair','single_document_reference_repair'].includes(selected.payload.family))throw new Error('Choose a source-grounded Village plan.');if(x.buildBusy)return true;x.buildBusy=true;const epoch=x.flowEpoch;try{await b.render();const response=await post('/api/guided/simulator',{plan_ref:x.planRef});if(epoch!==x.flowEpoch){b.toast('The earlier world is saved in the library. Your newer draft is still open.');return true;}x.simulatorRef=response.simulator_ref;save();await b.refresh();await b.render();}finally{if(epoch===x.flowEpoch){x.buildBusy=false;await b.render();}}return true;}
      if(target.hasAttribute('data-journey-run')){const selected=await read(x.simulatorRef,'guided_simulator'),plan=await read(selected.payload.plan_ref,'guided_plan');if(!['village_document_access_repair','single_document_reference_repair'].includes(plan.payload.family))throw new Error('Choose a source-grounded Village world.');if(x.runBusy)return true;x.runBusy=true;const epoch=x.flowEpoch;try{await b.render();const response=await post('/api/guided/run',{simulator_ref:x.simulatorRef});if(epoch!==x.flowEpoch){b.toast('The earlier experiment is saved. Your current source or draft stays open.');return true;}x.executionRef=response.execution_ref;x.study=response.result_ref;save();await b.refresh();await navigate('findings');ask('Explain this new real-agent experiment using its exact saved results. Describe the counts and uncertainty in simple language, then suggest the next test. Do not infer a mechanism or historical cause.',{proactive:true});}finally{if(epoch===x.flowEpoch){x.runBusy=false;await b.render();}}return true;}
      if(target.hasAttribute('data-journey-result')){const r=await read(x.executionRef,'guided_result');x.study=r.payload.result_ref;await navigate('findings');return true;}
      return false;
    }
    async function change(target){
      if(target.id==='journey-source'){x.connectSource=target.value;return true;}
      if(target.id==='journey-event-file'){const file=target.files?.[0];if(file){if(file.size>900000)throw new Error('Choose an event batch under 900 KB.');x.telemetryContent=await file.text();await b.render();}return true;}
      return false;
    }
    function input(target){if(target.id==='journey-events')x.telemetryContent=target.value;if(target.dataset?.journeyField){const key=target.dataset.journeyField;x.draft[key]=['trials_per_arm','max_rounds','valid_probability','seed'].includes(key)?Number(target.value):target.value;invalidate();const counts=document.getElementById('journey-note-counts');if(counts)counts.textContent=noteCounts();}}
    function noteCounts(){const count=value=>String(value || '').trim().split(/\s+/).filter(Boolean).length,a=count(x.draft.control_text),z=count(x.draft.treatment_text);return `Control: ${a} words. Intervention: ${z} words. ${a===z?'Length is matched; the meaning still differs.':'Length differs. This test will measure the whole note change, including its length.'}`;}
    let followBusy=false,lastFollow=0;
    async function update(){
      if(!x.followRun || followBusy || Date.now()-lastFollow<10000)return;followBusy=true;lastFollow=Date.now();
      try{const packet=await b.api('/api/observability/follow?run_id='+encodeURIComponent(x.followRun));if(packet.run_ref && packet.run_ref.hash!==x.watchRunRef?.hash){
        if(x.runBusy || x.buildBusy || x.watchStudy || ['plan','simulator','findings'].includes(b.app.view)){if(x.followPending?.run_ref?.hash!==packet.run_ref.hash){x.followPending=packet;b.toast('New swarm events are available. Your current plan and result keep their saved source. Connect again when you want to review the update.');}}
        else{await accept(packet);b.toast('New swarm events arrived. The briefing and replay have advanced to a new saved version.');}
      }}catch(_){}finally{followBusy=false;}
    }
    const views={connect,brief,plan,simulator};
    return {views,click,change,input,update,accept,applyDraft,save};
  }
  scope.ResearchJourney={create};if(typeof module!=='undefined')module.exports=scope.ResearchJourney;
})(typeof globalThis==='undefined'?window:globalThis);



